Footer
wolox-training/cb-react pull request #3
Opened 2017-12-21 18:03 UTC by carlosbollero

# Summary
Added footer section

# Trello card
[](https://trello.com/c/FGsZmOQh/16-footer)

# Screenshot
![footer](https://user-images.githubusercontent.com/7310056/34268578-0e0a132c-e660-11e7-80ef-32845cef6f87.png)

2017-12-22 13:05 UTC, carlosbollero commented
@meelrossi I merged everything to this branch so you can review just this one.

2017-12-22 18:04 UTC, meelrossi requested changes
Some changes. 
PD: In this case is the same, but for the future separate the pull requests by functionality because then you will be able to have some things merge in case there is a deploy or sth. If you start merging then the pull request will be really big and probably have a lot of changes, and will not allow you to have anything to show until all of it is reviewed and correct :D

2017-12-22 18:04 UTC, meelrossi commented on maquetado/index.html
> +		<img class="nv-logo" src="assets/wolox_logo.svg">
set closing mark to the img tag ```<img class="nv-logo" src="assets/wolox_logo.svg" />```

2017-12-22 18:04 UTC, meelrossi commented on maquetado/index.html
> +			<img class="triangle" src="assets/triangle.svg">
This si better if you put it directly with scss using ```::before``` as it is only for design purposes and doesn't change the layout. It will make your index file more readable.

2017-12-22 18:04 UTC, meelrossi commented on maquetado/index.html
> +				<span class="tech-title">ReactJS</span>
you can you ```h1``` tag here so that if there is an error importing css then the structure will let you know the priorities of the text. The same with the subtitle.

2017-12-22 18:04 UTC, meelrossi commented on maquetado/index.html
> +				<span class="tech-subtitle">Release: 2013</span>
```<h2>```

2017-12-22 18:04 UTC, meelrossi commented on maquetado/index.html
> +			<input class="form-input" type="text">
```<input class="form-input" type="text" />```

2017-12-22 18:04 UTC, meelrossi commented on maquetado/index.html
> +			<input class="form-button" type="submit" value="SEND">
<input class="form-button" type="submit" value="SEND"\>

2017-12-22 18:04 UTC, meelrossi commented on maquetado/scss/application.scss
> +$triangle-height: 90px;
Great! Maybe you can put this is another file like _sizes.scss

2017-12-22 18:04 UTC, meelrossi commented on maquetado/scss/application.scss
> +$triangle-height: 90px;
Also it is common to add this to a separate folder called variables. I forgot to tell you that in the previous pr. You could add sizes and colors to that folder. we use ```_``` to defined the file as a variables file

2017-12-22 18:04 UTC, meelrossi commented on maquetado/scss/application.scss
> +			margin: 0 0 0 -33px;
do not use margin with negative numbers. Set the triangle position to absolute and position it in reference of the container

2017-12-22 18:04 UTC, meelrossi commented on maquetado/scss/application.scss
> +.nav {
all of this goes to ```styles.scss```

2017-12-22 18:04 UTC, meelrossi commented on maquetado/scss/application.scss
> +			&:before {
```::before```

2017-12-22 18:04 UTC, meelrossi commented on maquetado/scss/application.scss
> +		flex-direction: row;
There is no need to specify the direction when its row

2017-12-26 14:12 UTC, meelrossi requested changes

2017-12-26 14:12 UTC, meelrossi commented on maquetado/index.html
> +			<!-- <img class="triangle" src="assets/triangle.svg"/> -->
remove the comment :D

2017-12-26 14:12 UTC, meelrossi commented on maquetado/index.html
> +			<input class="form-button" type="submit" value="SEND" />
this should be a ```<button>``` tag

2017-12-26 14:12 UTC, meelrossi commented on maquetado/scss/application.scss
> +.nav {
move all the info from this line till the end of the file to the ```styles.scss``` file

2017-12-26 14:12 UTC, meelrossi commented on maquetado/index.html
> +			<div class="triangle"></div>
set this with ::before selector

2017-12-26 17:00 UTC, meelrossi approved these changes

2017-12-26 17:03 UTC, merged